<form action="/index.php/<?php echo $block->getFormAction() ?>" method="post">
    <input name="firstname" type="text" placeholder="First Name" required>
    <input name="lastname" type="text" placeholder="Last Name" required>
    <input name="phone" type="number" placeholder="Phone" required>
    <input name="email" type="email" placeholder="Email" required>
    <input name="dob" type="date">
    <input type="submit" value="Save">
</form>